/slam_gmapping:
  ros__parameters:
    angularUpdate: 0.3
    astep: 0.05
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    laser_frame: laser
    delta: 0.01
    iterations: 5
    kernelSize: 1
    lasamplerange: 0.005
    lasamplestep: 0.005
    linearUpdate: 0.5
    llsamplerange: 0.01
    llsamplestep: 0.01
    lsigma: 0.075
    lskip: 0
    lstep: 0.05
    map_update_interval: 1.0
    maxRange: 12.0
    maxUrange: 6.0
    minimum_score: 0.01
    occ_thresh: 0.25
    ogain: 3.0
    particles: 300
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    resampleThreshold: 0.4
    sigma: 0.03
    srr: 0.05
    srt: 0.1
    str: 0.05
    stt: 0.05
    temporalUpdate: -1.0
    transform_publish_period: 0.05
    use_sim_time: false
    xmax: 8.0
    xmin: -8.0
    ymax: 8.0
    ymin: -8.0
