use_sim_time: true
alpha1: 0.2
alpha2: 0.2
alpha3: 0.2
alpha4: 0.2
alpha5: 0.2
base_frame_id: "base_link"
global_frame_id: "map"
laser_model_type: "likelihood_field"
max_particles: 2000
min_particles: 500
odom_frame_id: "odom"
tf_broadcast: true